parse IPv6 addresses and lua
factorysh/redistop pull request #3
Opened 2021-05-23 08:53 UTC by cquest

2021-05-23 12:54 UTC, athoune requested changes

2021-05-23 12:54 UTC, athoune commented on monitor/monitor.go
> +	line := regexp.MustCompile(`^\+(\d+\.\d+) \[(\d+) ([\d\.]+|\[[0-9a-f\:]+\]|lua):?(\d+)?\] "(.*?)"`)
Can you add 2 comments, one for ipv6 client, one for lua client, please.

2021-05-23 12:54 UTC, athoune commented on monitor/monitor.go
> +				port, err := strconv.Atoi("0"+l[4])
What is the meaning of a leading 0 for Atoi ?

2021-05-23 14:36 UTC, cquest commented on monitor/monitor.go
> +				port, err := strconv.Atoi("0"+l[4])
When the client is lua, there is not port number, so this creates a dummy 0 port number.

2021-05-23 14:37 UTC, cquest commented on monitor/monitor.go
> +	line := regexp.MustCompile(`^\+(\d+\.\d+) \[(\d+) ([\d\.]+|\[[0-9a-f\:]+\]|lua):?(\d+)?\] "(.*?)"`)
IPv6 contain hexadecimal \d is not enough.

2021-05-23 14:41 UTC, cquest commented on monitor/monitor.go
> +	line := regexp.MustCompile(`^\+(\d+\.\d+) \[(\d+) ([\d\.]+|\[[0-9a-f\:]+\]|lua):?(\d+)?\] "(.*?)"`)
Just added IPv6 and LUA examples.

2021-05-24 08:58 UTC, athoune approved these changes

2021-05-24 08:58 UTC, merged